name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write # Needed for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            binary: jsonping
          - os: linux
            arch: arm64
            binary: jsonping
          - os: linux
            arch: arm
            binary: jsonping

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o ${{ matrix.binary }}-${{ matrix.os }}-${{ matrix.arch }}
          chmod +x ${{ matrix.binary }}-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary }}-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ matrix.binary }}-${{ matrix.os }}-${{ matrix.arch }}
          compression-level: 9

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Prepare release files
        run: |
          mkdir release
          cp artifacts/jsonping-* release/
          cd release
          sha256sum jsonping-* > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release/*
          generate_release_notes: true
          draft: false
          prerelease: false
